#ifndef CANVASCONSTANTS_H
#define CANVASCONSTANTS_H

#define ANIMATORSCENE_USERAREA_WIDTH 60
#define ANIMATORSCENE_USERAREA_HEIGHT 60
#define INTERSTATS_SPACE 10
#define STATSSCENE_WIDTH_DEFAULT 1024
#define STATSSCENE_HEIGHT_DEFAULT 1024
#define GRID_LINES_DEFAULT 5
#define UTYPE 65536
#define ANIMNODE_TYPE (UTYPE + 100)
#define canvasNode_ZVALUE 0


#endif // CANVASCONSTANTS_H
